### PR TITLE
Fixes #3 - Added pcicrawler/lib directory

### LINKED ISSUE #2: Support for AER issues
Hi,

Thanks for releasing this tool! Looks neat.

Have you considered adding support for reading AER state? AER can be very messy to manually parse so having something like pcicrawler being able to make sense of it, especially at scale, would be neat.

Reference documentation: 
https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-pci-devices-aer_stats

### LINKED ISSUE #3: Error while running `pcicrawler` utility
While running the `pcicrawler` utility from within a virtual-environment - Following `ModuleNotFound` error is observed - 

```shell
(venv) gabhijit@gabhijit-GL553VD:~/backup/personal-code/pcicrawler$ pcicrawler
Traceback (most recent call last):
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/bin/pcicrawler", line 11, in <module>
    load_entry_point('pcicrawler==0.1.0', 'console_scripts', 'pcicrawler')()
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/gabhijit/backup/personal-code/pcicrawler/venv/lib/python3.7/site-packages/pcicrawler-0.1.0-py3.7.egg/pcicrawler/cli.py", line 12, in <module>
ModuleNotFoundError: No module named 'pcicrawler.lib'
```

Indeed there is no module named `lib` inside `pcicrawler`.

This error is observed while running from the checked out repo after doing a `setup.py install` in virtualenv.

### PR DESCRIPTION
**Pull request by gabhijit**
Likely - thanks to lib/ being ignored inside .gitignore `pcicrawler/lib`
directory was not added. This results in runtime error.

### CODE REVIEW

**Comment by gabhijit** [comment]
This is the output after the fix 

```shell
(venv) gabhijit@gabhijit-GL553VD:~/backup/personal-code/pcicrawler$ sudo venv/bin/pcicrawler 
0000:00:1c.0, PCIe root_port, Intel Corporation (8086) 100 Series/C230 Series Chipset Family PCI Express Root Port #3 (a112)
0000:00:1f.0, Intel Corporation (8086) HM175 Chipset LPC/eSPI Controller (a152)
0000:00:01.0, PCIe root_port, Intel Corporation (8086) Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (1901)
0000:00:08.0, Intel Corporation (8086) Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model (1911)
0000:00:14.0, Intel Corporation (8086) 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller (a12f)
0000:00:1f.2, Intel Corporation (8086) 100 Series/C230 Series Chipset Family Power Management Controller (a121)
0000:00:15.0, Intel Corporation (8086) 100 Series/C230 Series Chipset Family Serial IO I2C Controller #0 (a160)
0000:00:00.0, Intel Corporation (8086) Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (5910)
0000:00:1c.3, PCIe root_port, Intel Corporation (8086) 100 Series/C230 Series Chipset Family PCI Express Root Port #4 (a113)
0000:01:00.0, PCIe endpoint, NVIDIA Corporation (10de) GP107M [GeForce GTX 1050 Mobile] (1c8d)
  connected via: slot 1, root_port
0000:00:1c.6, PCIe root_port, Intel Corporation (8086) 100 Series/C230 Series Chipset Family PCI Express Root Port #7 (a116)
0000:02:00.0, PCIe endpoint, Intel Corporation (8086) Wireless 7265 (095a)
  connected via: slot 6, root_port
0000:04:00.0, PCIe endpoint, Realtek Semiconductor Co., Ltd. (10ec) RTS5229 PCI Express Card Reader (5229)
  connected via: slot 10, root_port
0000:00:17.0, Intel Corporation (8086) HM170/QM170 Chipset SATA Controller [AHCI Mode] (a103)
0000:00:16.0, Intel Corporation (8086) 100 Series/C230 Series Chipset Family MEI Controller #1 (a13a)
0000:00:1f.4, Intel Corporation (8086) 100 Series/C230 Series Chipset Family SMBus (a123)
0000:03:00.0, PCIe endpoint, Realtek Semiconductor Co., Ltd. (10ec) RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (8168)
  connected via: slot 7, root_port
0000:00:02.0, PCIe root_complex_endpoint, Intel Corporation (8086), device 591b
0000:00:1f.3, Intel Corporation (8086) CM238 HD Audio Controller (a171)
0000:00:14.2, Intel Corporation (8086) 100 Series/C230 Series Chipset Family Thermal Subsystem (a131)
(venv) gabhijit@gabhijit-GL553VD:~/backup/personal-code/pcicrawler$ 
```

**Review by ashwinp-fb — APPROVED** [review]
Thanks for the quick fix Abhijit!

**Comment by harsh17-in** [comment]
@gabhijit after your suggested edits, I am still facing issues.

C:\Python36\Scripts>python pcicrawler-script.py
Traceback (most recent call last):
  File "pcicrawler-script.py", line 11, in <module>
    load_entry_point('pcicrawler==0.1.0', 'console_scripts', 'pcicrawler')()
  File "C:\Python36\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python36\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python36\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python36\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python36\lib\site-packages\pcicrawler-0.1.0-py3.6.egg\pcicrawler\cli.py", line 184, in main
AttributeError: module 'os' has no attribute 'geteuid'

C:\Python36\Scripts>python pcicrawler.exe --help
  File "pcicrawler.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file pcicrawler.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I tried both way of launching the pcicrawler. Can you suggest the way to use too?

**Comment by ashwinp-fb** [comment]
Hi Harsh,
geteuid() is only available on unix like systems. What Operating system are you using?

**Comment by gabhijit** [comment]
@harsh17-in - I don't think this is supported on windows yet. I am assuming based on your copy-pasted output above.

**Comment by harsh17-in** [comment]
@gabhijit ohh...I was thinking I can use it on any platform.
Thanks anyway, Is there any releases supporting windows soon?

**Comment by gabhijit** [comment]
This particular pull request is redundant.

**Pull request closed without merging**
