### PR TITLE
Make it work.

### PR DESCRIPTION
**Pull request by feisuzhu**

### CODE REVIEW

**Review by ashwinp-fb — APPROVED** [review]
Thanks for adding automatic support for standard Ubuntu!
nit: Please update the title of this PR to be more informative, which will help in code archeology.

**Review by ashwinp-fb — CHANGES_REQUESTED** [review]
ROOT_UID_REQUIRED is actually 16 - this is the standard return code for this case.

**Comment by feisuzhu** [comment]
Hi, @ashwinp-fb 

I read the Facebook CLA and I think I can't sign it, but I would give up copyright for this particular PR.
If this PR seems relevant to you please commit your self, sorry.

**Comment by ashwinp-fb** [comment]
Thanks feisuzhu! This is relevant and useful. We will prioritize this fix soon.

**Pull request closed without merging**
